version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb
